// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Client represents an OAuth2 client.
type Client struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	Labels               []string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty"`
	Public               bool     `protobuf:"varint,4,opt,name=public" json:"public,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{0}
}
func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (dst *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(dst, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Client) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Client) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// CreateClientReq is a request to make a client.
type CreateClientReq struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientReq) Reset()         { *m = CreateClientReq{} }
func (m *CreateClientReq) String() string { return proto.CompactTextString(m) }
func (*CreateClientReq) ProtoMessage()    {}
func (*CreateClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{1}
}
func (m *CreateClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientReq.Unmarshal(m, b)
}
func (m *CreateClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientReq.Marshal(b, m, deterministic)
}
func (dst *CreateClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientReq.Merge(dst, src)
}
func (m *CreateClientReq) XXX_Size() int {
	return xxx_messageInfo_CreateClientReq.Size(m)
}
func (m *CreateClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientReq proto.InternalMessageInfo

func (m *CreateClientReq) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

// CreateClientResp returns the response from creating a client.
type CreateClientResp struct {
	AlreadyExists        bool     `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists" json:"already_exists,omitempty"`
	Client               *Client  `protobuf:"bytes,2,opt,name=client" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientResp) Reset()         { *m = CreateClientResp{} }
func (m *CreateClientResp) String() string { return proto.CompactTextString(m) }
func (*CreateClientResp) ProtoMessage()    {}
func (*CreateClientResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{2}
}
func (m *CreateClientResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResp.Unmarshal(m, b)
}
func (m *CreateClientResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResp.Marshal(b, m, deterministic)
}
func (dst *CreateClientResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResp.Merge(dst, src)
}
func (m *CreateClientResp) XXX_Size() int {
	return xxx_messageInfo_CreateClientResp.Size(m)
}
func (m *CreateClientResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResp proto.InternalMessageInfo

func (m *CreateClientResp) GetAlreadyExists() bool {
	if m != nil {
		return m.AlreadyExists
	}
	return false
}

func (m *CreateClientResp) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

// DeleteClientReq is a request to delete a client.
type DeleteClientReq struct {
	// The ID of the client.
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientReq) Reset()         { *m = DeleteClientReq{} }
func (m *DeleteClientReq) String() string { return proto.CompactTextString(m) }
func (*DeleteClientReq) ProtoMessage()    {}
func (*DeleteClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{3}
}
func (m *DeleteClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientReq.Unmarshal(m, b)
}
func (m *DeleteClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientReq.Marshal(b, m, deterministic)
}
func (dst *DeleteClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientReq.Merge(dst, src)
}
func (m *DeleteClientReq) XXX_Size() int {
	return xxx_messageInfo_DeleteClientReq.Size(m)
}
func (m *DeleteClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientReq proto.InternalMessageInfo

func (m *DeleteClientReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeleteClientResp determines if the client is deleted successfully.
type DeleteClientResp struct {
	NotFound             bool     `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientResp) Reset()         { *m = DeleteClientResp{} }
func (m *DeleteClientResp) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResp) ProtoMessage()    {}
func (*DeleteClientResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{4}
}
func (m *DeleteClientResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResp.Unmarshal(m, b)
}
func (m *DeleteClientResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResp.Marshal(b, m, deterministic)
}
func (dst *DeleteClientResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResp.Merge(dst, src)
}
func (m *DeleteClientResp) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResp.Size(m)
}
func (m *DeleteClientResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResp proto.InternalMessageInfo

func (m *DeleteClientResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

// VersionReq is a request to fetch version info.
type VersionReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionReq) Reset()         { *m = VersionReq{} }
func (m *VersionReq) String() string { return proto.CompactTextString(m) }
func (*VersionReq) ProtoMessage()    {}
func (*VersionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{5}
}
func (m *VersionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReq.Unmarshal(m, b)
}
func (m *VersionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReq.Marshal(b, m, deterministic)
}
func (dst *VersionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReq.Merge(dst, src)
}
func (m *VersionReq) XXX_Size() int {
	return xxx_messageInfo_VersionReq.Size(m)
}
func (m *VersionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReq.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReq proto.InternalMessageInfo

// VersionResp holds the version info of components.
type VersionResp struct {
	// Semantic version of the server.
	Server string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	// Numeric version of the API. It increases everytime a new call is added to the API.
	// Clients should use this info to determine if the server supports specific features.
	Api                  int32    `protobuf:"varint,2,opt,name=api" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResp) Reset()         { *m = VersionResp{} }
func (m *VersionResp) String() string { return proto.CompactTextString(m) }
func (*VersionResp) ProtoMessage()    {}
func (*VersionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_539b97923c2380a0, []int{6}
}
func (m *VersionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResp.Unmarshal(m, b)
}
func (m *VersionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResp.Marshal(b, m, deterministic)
}
func (dst *VersionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResp.Merge(dst, src)
}
func (m *VersionResp) XXX_Size() int {
	return xxx_messageInfo_VersionResp.Size(m)
}
func (m *VersionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResp.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResp proto.InternalMessageInfo

func (m *VersionResp) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *VersionResp) GetApi() int32 {
	if m != nil {
		return m.Api
	}
	return 0
}

func init() {
	proto.RegisterType((*Client)(nil), "api.Client")
	proto.RegisterType((*CreateClientReq)(nil), "api.CreateClientReq")
	proto.RegisterType((*CreateClientResp)(nil), "api.CreateClientResp")
	proto.RegisterType((*DeleteClientReq)(nil), "api.DeleteClientReq")
	proto.RegisterType((*DeleteClientResp)(nil), "api.DeleteClientResp")
	proto.RegisterType((*VersionReq)(nil), "api.VersionReq")
	proto.RegisterType((*VersionResp)(nil), "api.VersionResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LuxaforceClient is the client API for Luxaforce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LuxaforceClient interface {
	// CreateClient creates a client.
	CreateClient(ctx context.Context, in *CreateClientReq, opts ...grpc.CallOption) (*CreateClientResp, error)
	// DeleteClient deletes the provided client.
	DeleteClient(ctx context.Context, in *DeleteClientReq, opts ...grpc.CallOption) (*DeleteClientResp, error)
	// CreatePassword creates a password.
	GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionResp, error)
}

type luxaforceClient struct {
	cc *grpc.ClientConn
}

func NewLuxaforceClient(cc *grpc.ClientConn) LuxaforceClient {
	return &luxaforceClient{cc}
}

func (c *luxaforceClient) CreateClient(ctx context.Context, in *CreateClientReq, opts ...grpc.CallOption) (*CreateClientResp, error) {
	out := new(CreateClientResp)
	err := c.cc.Invoke(ctx, "/api.Luxaforce/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luxaforceClient) DeleteClient(ctx context.Context, in *DeleteClientReq, opts ...grpc.CallOption) (*DeleteClientResp, error) {
	out := new(DeleteClientResp)
	err := c.cc.Invoke(ctx, "/api.Luxaforce/DeleteClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luxaforceClient) GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionResp, error) {
	out := new(VersionResp)
	err := c.cc.Invoke(ctx, "/api.Luxaforce/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LuxaforceServer is the server API for Luxaforce service.
type LuxaforceServer interface {
	// CreateClient creates a client.
	CreateClient(context.Context, *CreateClientReq) (*CreateClientResp, error)
	// DeleteClient deletes the provided client.
	DeleteClient(context.Context, *DeleteClientReq) (*DeleteClientResp, error)
	// CreatePassword creates a password.
	GetVersion(context.Context, *VersionReq) (*VersionResp, error)
}

func RegisterLuxaforceServer(s *grpc.Server, srv LuxaforceServer) {
	s.RegisterService(&_Luxaforce_serviceDesc, srv)
}

func _Luxaforce_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuxaforceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Luxaforce/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuxaforceServer).CreateClient(ctx, req.(*CreateClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luxaforce_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuxaforceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Luxaforce/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuxaforceServer).DeleteClient(ctx, req.(*DeleteClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Luxaforce_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuxaforceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Luxaforce/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuxaforceServer).GetVersion(ctx, req.(*VersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Luxaforce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Luxaforce",
	HandlerType: (*LuxaforceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _Luxaforce_CreateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _Luxaforce_DeleteClient_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Luxaforce_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_539b97923c2380a0) }

var fileDescriptor_api_539b97923c2380a0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x25, 0x01, 0x22, 0x32, 0x50, 0x88, 0xac, 0xb6, 0x8a, 0xe8, 0x85, 0xba, 0xaa, 0xc4, 0x29,
	0x55, 0xa9, 0xd4, 0x9e, 0x7a, 0x29, 0xfd, 0xb8, 0xf4, 0x94, 0x43, 0x8f, 0x45, 0x26, 0x19, 0x54,
	0x4b, 0x26, 0x36, 0xb6, 0xa9, 0xd8, 0xff, 0xb6, 0x3f, 0x6e, 0x65, 0xc7, 0xbb, 0x9b, 0xa0, 0xdd,
	0x9b, 0xdf, 0x9b, 0x79, 0x33, 0xf3, 0x5e, 0x02, 0x29, 0x53, 0xbc, 0x50, 0x5a, 0x5a, 0x49, 0x86,
	0x4c, 0x71, 0x6a, 0x21, 0xd9, 0x0a, 0x8e, 0x8d, 0x25, 0x73, 0x88, 0x79, 0x9d, 0x47, 0xab, 0x68,
	0x9d, 0x96, 0x31, 0xaf, 0xc9, 0x6b, 0x48, 0x0c, 0x56, 0x1a, 0x6d, 0x1e, 0x7b, 0x2e, 0x20, 0xc7,
	0x0b, 0xb6, 0x47, 0x61, 0xf2, 0xe1, 0x6a, 0xe8, 0xf8, 0x16, 0x39, 0x5e, 0x9d, 0xf7, 0x82, 0x57,
	0xf9, 0x68, 0x15, 0xad, 0x27, 0x65, 0x40, 0x84, 0xc0, 0xa8, 0x61, 0x47, 0xcc, 0xc7, 0x7e, 0x8a,
	0x7f, 0xd3, 0xcf, 0xb0, 0xd8, 0x6a, 0x64, 0x16, 0xdb, 0xdd, 0x25, 0x9e, 0xc8, 0x3b, 0x48, 0x2a,
	0x0f, 0xfc, 0x09, 0xd3, 0xcd, 0xb4, 0x70, 0x97, 0x86, 0x7a, 0x28, 0xd1, 0xbf, 0x90, 0xf5, 0x75,
	0x46, 0x91, 0xf7, 0x30, 0x67, 0x42, 0x23, 0xab, 0x6f, 0x76, 0x78, 0xe1, 0xc6, 0x1a, 0x3f, 0x60,
	0x52, 0xbe, 0x08, 0xec, 0x0f, 0x4f, 0x76, 0xe6, 0xc7, 0xcf, 0xcf, 0x7f, 0x0b, 0x8b, 0xef, 0x28,
	0xb0, 0x7b, 0xd7, 0x55, 0x2c, 0xf4, 0x03, 0x64, 0xfd, 0x16, 0xa3, 0xc8, 0x1b, 0x48, 0x1b, 0x69,
	0x77, 0x07, 0x79, 0x6e, 0xea, 0xb0, 0x7d, 0xd2, 0x48, 0xfb, 0xd3, 0x61, 0x3a, 0x03, 0xf8, 0x83,
	0xda, 0x70, 0xd9, 0x94, 0x78, 0xa2, 0x5f, 0x60, 0xfa, 0x80, 0x8c, 0x6a, 0x43, 0xd6, 0xff, 0x51,
	0x87, 0x0d, 0x01, 0x91, 0x0c, 0xdc, 0xd7, 0xf1, 0xa7, 0x8e, 0x4b, 0xf7, 0xdc, 0xdc, 0x46, 0x90,
	0xfe, 0x3e, 0x5f, 0xd8, 0x41, 0xea, 0x0a, 0xc9, 0x57, 0x98, 0x75, 0x83, 0x20, 0x2f, 0x5b, 0x37,
	0xfd, 0x4c, 0x97, 0xaf, 0x9e, 0x60, 0x8d, 0xa2, 0x03, 0x27, 0xef, 0x9a, 0x08, 0xf2, 0x2b, 0xeb,
	0x41, 0x7e, 0xed, 0x96, 0x0e, 0xc8, 0x47, 0x80, 0x5f, 0x68, 0x83, 0x0f, 0xb2, 0xf0, 0x6d, 0x8f,
	0x1e, 0x97, 0x59, 0x9f, 0x70, 0x92, 0x6f, 0x4b, 0xc8, 0xb9, 0x2c, 0xcc, 0x3f, 0x14, 0x47, 0xd6,
	0x14, 0xe2, 0xde, 0x88, 0xeb, 0xdc, 0x27, 0xfe, 0x7f, 0xfc, 0x74, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x0d, 0xbe, 0x1f, 0xdf, 0x9c, 0x02, 0x00, 0x00,
}
